name: timmer
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  connectivity: ^3.0.6
  flutter:
    sdk: flutter
  http: ^1.1.0
  numberpicker: ^2.1.2
  permission_handler: ^11.0.1
  wifi_info_flutter: ^2.0.2
  wifi_iot: ^0.3.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo.png
